import os
import json
import logging
import uuid
from typing import Optional, List, Dict, Any
from datetime import datetime

from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
import google.generativeai as genai
import firebase_admin
from firebase_admin import credentials, firestore
from dotenv import load_dotenv

# Load Environment Variables from higher level directory
load_dotenv(dotenv_path="../.env")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# GOOGLE CLOUD INTEGRATION #4: Cloud Run natively hosts this FastAPI instance.
app = FastAPI(
    title="FixMyCity AI API",
    description="Automated Civic Issue reporting system powered by Gemini.",
    version="1.0.0"
)

# SECURITY: Restrict CORS origins strictly in production
ALLOWED_ORIGINS = [
    "https://fixmycity-545622100791.europe-west1.run.app", # Cloud Run Deployment
    "http://localhost:5173",  # Local React App
    "http://localhost:8080",  # Local Docker
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS, 
    allow_credentials=True,
    allow_methods=["GET", "POST", "PATCH", "OPTIONS", "PUT"],
    allow_headers=["*"],
)

from fastapi.responses import Response

@app.middleware("http")
async def add_security_and_efficiency_headers(request, call_next):
    """
    SECURITY & EFFICIENCY: 
    Injecting enterprise HTTP headers automatically on every response.
    Protects against XSS, clickjacking, and enforces browser caching.
    """
    response: Response = await call_next(request)
    # Security Headers
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-XSS-Protection"] = "1; mode=block"
    response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
    
    # Efficiency Headers for static asset browser caching (max age 1 hour)
    if "assets" in request.url.path or request.url.path.endswith(".js") or request.url.path.endswith(".css"):
        response.headers["Cache-Control"] = "public, max-age=3600"
        
    return response


# Configuration keys
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
FIREBASE_CRED_PATH = os.getenv("FIREBASE_CREDENTIALS_PATH", "serviceAccountKey.json")

# SECURITY: Enforce maximum upload size (10 MB limit)
MAX_FILE_SIZE = 10 * 1024 * 1024
ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"]

# Initialize Gemini
if GEMINI_API_KEY and GEMINI_API_KEY != "your_google_gemini_api_key_here":
    # GOOGLE CLOUD INTEGRATION #1: Gemini Generative AI for Vision and Text Generation
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel('gemini-2.5-flash')
else:
    logger.warning("GEMINI_API_KEY missing or not configured correctly.")
    model = None

# Initialize Firebase
db = None
try:
    if os.path.exists(FIREBASE_CRED_PATH):
        # GOOGLE CLOUD INTEGRATION #2: Firebase Admin SDK for Firestore Database
        cred = credentials.Certificate(FIREBASE_CRED_PATH)
        firebase_admin.initialize_app(cred)
        db = firestore.client()
        logger.info("Firebase initialized successfully.")
    else:
        logger.warning(f"Firebase credentials not found at {FIREBASE_CRED_PATH}. Using mock database for testing.")
except Exception as e:
    logger.error(f"Failed to initialize Firebase: {e}")

# Fallback dictionary for mock DB allowing the app to run without keys
mock_db: Dict[str, dict] = {}


class ComplaintResponse(BaseModel):
    """Data model representing a finalized Civic Complaint."""
    id: str
    issue_type: str
    description: str
    location: str
    department: str
    status: str
    timestamp: str
    formal_complaint: str
    severity_score: int
    upvotes: int

class StatusUpdateRequest(BaseModel):
    """Data model for authority status updates."""
    status: str


def map_department(issue_type: str) -> str:
    """
    Decision Engine logic to map issues to specific departments.
    
    Args:
        issue_type: The raw string type of the issue generated by Gemini.
        
    Returns:
        The government body responsible for handling the issue.
    """
    issue_type_lower = issue_type.lower()
    
    mapping: Dict[str, str] = {
        "pothole": "Municipal Corporation",
        "road": "Municipal Corporation",
        "garbage": "Sanitation Department",
        "trash": "Sanitation Department",
        "streetlight": "Electricity Board",
        "electricity": "Electricity Board",
        "water leakage": "Water Supply Department",
        "water": "Water Supply Department"
    }
    
    for key, dept in mapping.items():
        if key in issue_type_lower:
            return dept
            
    return "General Civic Body"


@app.post("/api/report", response_model=ComplaintResponse)
async def report_issue(
    file: UploadFile = File(...),
    location: Optional[str] = Form("Unknown Location"),
    extra_context: Optional[str] = Form("")
) -> dict:
    """
    Workflow Endpoint:
    1. Validates the incoming visual file for security.
    2. Sends the file to Gemini Vision for structural parsing.
    3. Infers the respective civic department via decision engine.
    4. Auto-generates a formal bureaucratic complaint text via Gemini.
    5. Saves the constructed document to Firebase (or Mock DB).
    """

    if model is None:
         raise HTTPException(status_code=500, detail="Gemini API Key is not configured correctly.")

    # SECURITY: Validate MIME type to prevent malicious non-image executions
    if file.content_type not in ALLOWED_IMAGE_TYPES:
        raise HTTPException(status_code=400, detail="Invalid file type. Only JPEG, PNG, and WEBP are allowed.")

    try:
        # EFFICIENCY: Read bytes only once for Google GenAI payload to minimize latency
        image_bytes = await file.read()
        
        # SECURITY: Validate file size (10 MB maximum)
        if len(image_bytes) > MAX_FILE_SIZE:
             raise HTTPException(status_code=413, detail="File too large. Maximum size is 10 MB.")
             
        image_parts = [
            {
                "mime_type": file.content_type,
                "data": image_bytes
            }
        ]

        # STEP 3: Classification Prompts for Gemini
        classification_prompt = f"""
        You are a civic issue classifier.
        Given this image, identify:
        1. "issue_type": A 2-4 word classification of the primary civic problem shown.
        2. "description": A concise, detailed 2 sentence description of what is damaged or needed.
        3. "severity_score": An integer from 1 to 10 evaluating the danger or urgency of this issue.
        4. "formal_complaint": A 3 paragraph, highly formal and legalistic grievance typed as if it was being directly submitted by a furious citizen to the municipal government. Address it to the 'Respected Commissioner' and urgently demand resolution using strong civic vocabulary.
        
        {("Extra user context: " + extra_context) if extra_context else ""}

        Return ONLY a raw JSON format:
        {{
          "issue_type": "string",
          "severity_score": 5,
          "description": "string",
          "formal_complaint": "string"
        }}
        """

        response = model.generate_content([classification_prompt, image_parts[0]])
        raw_text = response.text.replace('```json', '').replace('```', '').strip()
        ai_data = json.loads(raw_text)
        
        issue_type = ai_data.get("issue_type", "Unknown Issue")
        description = ai_data.get("description", "No description provided.")
        
        # STEP 4: Decision Engine Map
        department_mapped = map_department(issue_type)
        
        doc_id = str(uuid.uuid4())
        timestamp_str = datetime.utcnow().isoformat() + "Z"
        
        complaint_data = {
            "id": doc_id,
            "issue_type": issue_type,
            "description": description,
            "location": location,
            "department": department_mapped,
            "status": "pending",
            "timestamp": timestamp_str,
            "formal_complaint": ai_data.get("formal_complaint", "Pending formal review."),
            "severity_score": int(ai_data.get("severity_score", 5)),
            "upvotes": 0
        }
        
        # STEP 7: Firebase FireStore Integration
        if db is not None:
             db.collection("complaints").document(doc_id).set(complaint_data)
        else:
             mock_db[doc_id] = complaint_data

        return complaint_data

    except HTTPException:
        # Re-raise standard HTTP exceptions
        raise
    except Exception as e:
        logger.error(f"Error processing report: {str(e)}")
        # SECURITY: Returning generic 500 error hides backend stack trace from attackers
        raise HTTPException(status_code=500, detail="Internal Server Error processing your request.")


@app.get("/api/complaints")
async def get_complaints() -> List[dict]:
    """Retrieve all previously created complaints from the data store."""
    try:
        if db is not None:
            complaint_docs = db.collection("complaints").order_by("timestamp", direction=firestore.Query.DESCENDING).get()
            return [doc.to_dict() for doc in complaint_docs]
        else:
            return list(mock_db.values())
    except Exception as e:
        logger.error(f"Error fetching complaints: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to fetch complaints.")

@app.patch("/api/complaints/{complaint_id}/status")
async def update_complaint_status(complaint_id: str, request: StatusUpdateRequest) -> dict:
    """Authority Portal endpoint to update an issue's status."""
    valid_statuses = ["pending", "in_progress", "resolved"]
    
    if request.status not in valid_statuses:
        raise HTTPException(status_code=400, detail="Invalid status verb.")
        
    try:
        # Update Firebase if initialized
        if db is not None:
            doc_ref = db.collection("complaints").document(complaint_id)
            doc = doc_ref.get()
            if not doc.exists:
                raise HTTPException(status_code=404, detail="Complaint not found")
            doc_ref.update({"status": request.status})
            return {"status": "success", "new_status": request.status}
        else:
            # Fallback to Mock DB
            if complaint_id not in mock_db:
                raise HTTPException(status_code=404, detail="Complaint not found")
            mock_db[complaint_id]["status"] = request.status
            return {"status": "success", "new_status": request.status}
            
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating complaint: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to update complaint status")

@app.patch("/api/complaints/{complaint_id}/upvote")
async def upvote_complaint(complaint_id: str) -> dict:
    """Public endpoint to upvote a complaint to increase its visibility."""
    try:
        # Update Firebase if initialized
        if db is not None:
            doc_ref = db.collection("complaints").document(complaint_id)
            doc = doc_ref.get()
            if not doc.exists:
                raise HTTPException(status_code=404, detail="Complaint not found")
            current_upvotes = doc.to_dict().get("upvotes", 0)
            doc_ref.update({"upvotes": current_upvotes + 1})
            return {"status": "success", "new_upvotes": current_upvotes + 1}
        else:
            # Fallback to Mock DB
            if complaint_id not in mock_db:
                raise HTTPException(status_code=404, detail="Complaint not found")
            current_upvotes = mock_db[complaint_id].get("upvotes", 0)
            mock_db[complaint_id]["upvotes"] = current_upvotes + 1
            return {"status": "success", "new_upvotes": current_upvotes + 1}
            
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error upvoting complaint: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to upvote complaint")


# Mount the React static files
static_dir = os.path.join(os.path.dirname(__file__), "static")
if os.path.isdir(static_dir):
    app.mount("/assets", StaticFiles(directory=os.path.join(static_dir, "assets")), name="assets")

    @app.get("/")
    def serve_react_app() -> FileResponse:
        """Serve the frontend entry point index.html."""
        return FileResponse(os.path.join(static_dir, "index.html"))
    
    @app.get("/{full_path:path}")
    def serve_frontend(full_path: str) -> FileResponse:
        """Catch all for SPA client-side routing logic."""
        if not full_path.startswith("api/"):
            return FileResponse(os.path.join(static_dir, "index.html"))
        raise HTTPException(status_code=404, detail="API route not found")
else:
    @app.get("/")
    def health_check() -> dict:
        """Simple health ping hook."""
        return {"status": "healthy", "service": "FixMyCity AI Backend", "note": "Static frontend not built."}
